### ISSUE TITLE
Decreto motos Ibagué

### ISSUE THREAD

**Issue by MauricioRobayo** [MauricioRobayo/pypweb#197]
> En su página aparece pico y placa para las motos pero no soportan la información en ningún decreto expedido por la autoridad competente.

> Me refiero a la ciudad de Ibagué

**Comment by aptammy** [comment]
Hola si aparece el decreto de marzo de 2020 no se es si haya uno nuevo pero
el decrero está

**Comment by aptammy** [comment]
Es más mira
